# Generated by Django 3.2.6 on 2021-09-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='fotos',
            new_name='foto',
        ),
    ]
